version: 2
jobs:
  build_test:
    docker:
      - image: quay.io/token/go-build:v0.3.0
    working_directory: /home/circleci/github.com/tokencard/contracts
    steps:
      - checkout
      - restore_cache:
          keys:
          - vendor-{{ checksum "go.sum" }}
      - run: go mod vendor
      - run: go test -v ./...
      - save_cache:
          key: vendor-{{ checksum "go.sum" }}
          paths:
            - "vendor"

  build_check:
    machine: true
    working_directory: /home/circleci/github.com/tokencard/contracts
    steps:
      - checkout
      - restore_cache:
          keys:
            - vendor-{{ checksum "go.sum" }}
      - run: ./build.sh
      - run: '[[ -z $(git status -uno --porcelain) ]] || (git status ; echo "Please run ./build.sh before committing changes!"; exit 1)'

  mythril:
    docker:
      - image: mythril/myth:0.19.4
    working_directory: /src
    steps:
      - checkout
      - run: myth --max-depth 500 -x ./contracts/*.sol
      - run: myth --max-depth 500 -x ./contracts/internal/*.sol

  snyk_check:
    docker:
      - image: quay.io/token/go-build:v0.3.0
    working_directory: /go/src/github.com/tokencard/contracts
    steps:
      - checkout
      - run: apk add -U --no-cache nodejs nodejs-npm
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: dep init --no-examples
      - run: npm config set unsafe-perm true
      - run: npm install -g snyk@1.101.1
      - run: snyk auth ${SNYK_TOKEN}
      - run: snyk test --org=token

workflows:
  version: 2
  build_deploy:
    jobs:
      - build_test:
          filters:
            tags:
              ignore: ""
      - build_check:
          requires:
            - build_test
          filters:
            tags:
              ignore: ""
      - mythril:
          filters:
            tags:
              ignore: ""
      - snyk_check:
          context: snyk
